Small map fixes
BurgerLUA/burgerstation pull request #157
Opened 2021-02-23 09:31 UTC by PrimeGenerations

# What this PR does

Fixes being able to use dropship from outstide.

Makes Charlie Airlock immortal. Bye bye bubblegum corpse destroyer of airlocks.

# Why it should be added to the game

Fixes

2021-02-23 09:40 UTC, skigear commented
being able to get on the shuttle's back before it takes off isn't really an issue, other than that it can make getting on it easier

adding this would also get rid of jumping into bluespace, which is a mechanic that also doesn't cause much issue

2021-02-24 03:15 UTC, BurgerLUA requested changes
What specifically did you do to make the airlock immortal? Also why are the ammo restockers anchored now?

2021-02-24 03:15 UTC, BurgerLUA commented on maps/core/burgerstation.dmm
> +	anchored = 1
Wait, why is this anchored?

2021-02-24 03:15 UTC, BurgerLUA commented on maps/core/burgerstation.dmm
> +	anchored = 1
this too

2021-03-16 23:06 UTC, BurgerLUA commented
PR is 22 days stale with conflicting files, so I'm closing it.

2021-03-16 23:06 UTC, closed without merging