please send help, base for totems
BurgerLUA/burgerstation pull request #175
Opened 2021-03-07 04:42 UTC by jjpark-kb

# What this PR does
adds totemic tomes
adds totems which provide certain buffs (current have the 3 health regens)

# Why it should be added to the game
continue adding magic content, especially a supporting mage class

2021-03-08 04:11 UTC, jjpark-kb commented
I think that is enough content for a base PR

2021-03-08 09:53 UTC, BurgerLUA requested changes

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/item/weapon/ranged/magic/tomes/summon/totem/_totem.dm
> +	return ..()
This should just be ``. = ..()``

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +	desc = "None."
A short description should be added for each of the totem types.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +/obj/structure/totem/Destroy()
This should also contain ``owner = null`` after ``owner.totem = null``

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/mob/living/_living.dm
> +	var/obj/structure/totem/totem //This object's totem.
``QDEL_NULL(totem)`` should be called in ``mob/living/Destroy()`` somewhere

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		Destroy()
``Destroy()`` should not directly be called. ``qdel(src)`` should be called instead.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/healing/H = new(L.loc,10,COLOR_RED)
You should use ``CREATE(/obj/effect/temp/healing/,get_turf(L))`` instead and remove the ``INITIALIZE(H)`` and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_RED)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/healing/H = new(L.loc,10,COLOR_GREEN)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_GREEN)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/healing/H = new(L.loc,10,COLOR_BLUE)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_BLUE)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_RED)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_BLUE)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		L.Move(get_step(L.loc,get_dir(src,L)))
A little nervous about calling Move directly like this but we'll have to see if this causes any exploits.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		var/obj/effect/temp/electricity/H = new(L.loc,10,COLOR_BLUE)
You should use CREATE(/obj/effect/temp/healing/,get_turf(L)) instead and remove the INITIALIZE(H) and friends.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		L.Move(get_step(L.loc,get_dir(L,src)))
There might be an issue where someone might be on top of the totem and ``Move`` will be a redundant call. You should compare the two locs together to see if someone should actually move.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		L.Move(get_step(L.loc,get_dir(src,L)))
Also, you should call ``if(!isturf(L.loc) continue`` before the movement in cases where the living target might actually be in something else, like a crate or a vehicle.

2021-03-08 09:53 UTC, BurgerLUA commented on code/_core/obj/structure/totem.dm
> +		L.Move(get_step(L.loc,get_dir(L,src)))
Also, you should call ``if(!isturf(L.loc) continue`` before the movement in cases where the living target might actually be in something else, like a crate or a vehicle.

2021-03-08 09:54 UTC, BurgerLUA commented
Very good PR, by the way.

2021-03-08 11:41 UTC, jjpark-kb commented
I tested it and it worked before I did the changes.
I HAVE NOT tested it just yet with these changes.

2021-03-08 20:43 UTC, jjpark-kb commented
okay, tested. Works.

2021-03-08 20:47 UTC, jjpark-kb commented
the longer this PR is up, the more I hunger to create more totems 👀

2021-03-09 07:35 UTC, BurgerLUA approved these changes

2021-03-09 07:35 UTC, BurgerLUA commented on code/_core/mob/living/_living.dm
> +		totem = null
Don't need the null here but I can remove this when merging.

2021-03-09 07:35 UTC, merged