adds simple telescience
BurgerLUA/burgerstation pull request #193
Opened 2021-03-18 04:21 UTC by jjpark-kb

# What this PR does
title

# Why it should be added to the game
additional methods of transporting (whether they are dead or not)

2021-03-22 03:19 UTC, BurgerLUA requested changes

2021-03-22 03:19 UTC, BurgerLUA commented on code/_core/obj/item/analyzer/angle.dm
> +	assigned_number = rand(111111,999999)
use ``name = CHECK_NAME("global positioning system")`` instead of this

2021-03-22 03:19 UTC, BurgerLUA commented on code/_core/obj/structure/interactive/teleporter.dm
> +	for(var/k2 in gps_list)
You should make an assoc list where the number (converted to string) is the key and the gps object is the value. It's faster and better for performance this way.

2021-03-22 23:49 UTC, BurgerLUA approved these changes
Will be merged tomorrow.

2021-03-22 23:49 UTC, BurgerLUA commented
Oh, there are conflicts with the map.

2021-03-23 00:10 UTC, jjpark-kb commented
> Oh, there are conflicts with the map.

fuuuuuuuu-- ill fix it.

2021-03-23 23:32 UTC, BurgerLUA approved these changes

2021-03-23 23:32 UTC, merged