Unoriginally named antag faction update
BurgerLUA/burgerstation pull request #217
Opened 2021-04-09 19:06 UTC by Stalkeros2

# What this PR does
Adds loot drops to both Syndicate and revs, introduces new currency for revs (that has no icon in vendors for some reason and also has no mapped in vendors so you gotta replace syndies vendors with revs ones and then remove their TCs), adds SKAT-10 aka NT's SKAT.

# Why it should be added to the game
More content good, makes rev and syndi waves actually viable now.

2021-04-18 08:29 UTC, Stalkeros2 commented
merg when

2021-04-22 06:02 UTC, BurgerLUA requested changes

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +	if (sealed == TRUE)
This should be just ``if(sealed)`` as ``== TRUE`` is redundent

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +		return
Should be return FALSE

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +	if (sealed == TRUE)
This should be just if(sealed) as == TRUE is redundent

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +	else
else here is redundent.

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +	if (sealed == TRUE)
This should be just if(sealed) as == TRUE is redundent

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +		return
should be return FALSE

2021-04-22 06:02 UTC, BurgerLUA commented on code/_core/obj/item/container/beaker/syringe.dm
> +	else
else here is redundent

2021-04-23 02:38 UTC, Stalkeros2 commented
Les gooooooo.

2021-04-23 03:54 UTC, Stalkeros2 commented on code/_core/datum/status_effect/_status_effect.dm
> +
:thinking:

2021-04-25 06:59 UTC, Stalkeros2 commented
AFK a little bit so it's gonna be delayed for a while. :pensive:

2021-05-14 02:44 UTC, jjpark-kb commented
You will need to go through all of the files and resolve the conflicts.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/head/helmet/hardsuit/russian.dm
> +		BOMB = AP_AXE
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/head/helmet/hardsuit/russian.dm
> +		ARCANE = -AP_GREATAXE*0.8,
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/head/helmet/hardsuit/syndicate.dm
> +		PAIN = AP_CLUB
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/overwear/hardsuit/russian.dm
> +		ARCANE = -AP_GREATAXE*0.8,
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/overwear/hardsuit/russian.dm
> +		BOMB = AP_AXE
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-14 02:45 UTC, jjpark-kb commented on code/_core/obj/item/clothing/overwear/hardsuit/syndicate.dm
> +		PAIN = AP_CLUB
AP_[NAME] is no longer valid, please consult similar items for defense ratings.

2021-05-25 10:07 UTC, Stalkeros2 commented
Whew, I'm finally not dead.

2021-06-24 10:40 UTC, Stalkeros2 commented
LETS FUCKING GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2021-06-24 10:50 UTC, Stalkeros2 commented
Okay no I'd rather start a new one because this one is fucked beyond recognition.

2021-06-24 10:51 UTC, closed without merging