Updates math.dm to what TG has
BurgerLUA/burgerstation pull request #672
Opened 2024-01-24 14:53 UTC by Xander3359

# What this PR does
Updates math.dm to whatever TG has
It is now named maths.dm (to match TG's filename)

# Why it should be added to the game
Updated code, stay modern coders 😎

2024-01-24 20:59 UTC, BurgerLUA requested changes
since the file was renamed from math to maths, it is no longer included in the .dme

2024-01-25 03:54 UTC, Xander3359 commented
> since the file was renamed from math to maths, it is no longer included in the .dme

I addressed this issue in the latest commit.
I initially was very confused because I couldn't find the .dme file somehow? 
But that was an error on my part since I found it now.

2024-01-25 06:07 UTC, BurgerLUA approved these changes

2024-01-26 21:55 UTC, merged

2024-01-31 03:54 UTC, LemonInTheDark commented
This pr breaks our license